### ISSUE TITLE
Once I add any text block as header, I cant switch it back to text or list.

### ISSUE THREAD

**Issue by navkamplikar** [akash-mitra/webtheory#31]
Once I add any text block as header, I cant switch it back to text or list. The only option is to delete the entire block and add a fresh.
[WebTheory - Admin Panel - Google Chrome 2020-03-03 23-53-06.zip](https://github.com/akash-mitra/webtheory/files/4282240/WebTheory.-.Admin.Panel.-.Google.Chrome.2020-03-03.23-53-06.zip)

**Comment by akash-mitra** [comment]
https://github.com/editor-js/header/issues/38

**Comment by akash-mitra** [comment]
resolved
