### ISSUE TITLE
List block in Edit mode has been changed to Text Block in the Read only mode

### ISSUE THREAD

**Issue by navkamplikar** [akash-mitra/webtheory#33]
List block in Edit mode has been changed to Text Block in the Read only mode
Even the Bold fonts are changed to normal (H4 headings).

Refer to the video attached.
[WebTheory - Admin Panel - Google Chrome 2020-03-04 00-37-54.zip](https://github.com/akash-mitra/webtheory/files/4282480/WebTheory.-.Admin.Panel.-.Google.Chrome.2020-03-04.00-37-54.zip)

**Comment by akash-mitra** [comment]
done
