### ISSUE TITLE
Image upload failed

### ISSUE THREAD

**Issue by navkamplikar** [akash-mitra/webtheory#36]
Image Tool: uploading failed because of {body: "<html>
↵<head><title>413 Request Entity Too Large<…disable MSIE and Chrome friendly error page -->
↵", code: 413, headers: {…}}

**Comment by sarubhai** [comment]
This is due to nginx post size i think

**Comment by akash-mitra** [comment]
added `client_max_body_size 25M;`

**Comment by akash-mitra** [comment]
@navkamplikar please test and close

**Comment by navkamplikar** [comment]
Working fine now

**Comment by navkamplikar** [comment]
I happened to see this issue again now. Attaching steps below.
[Img upload issue.zip](https://github.com/akash-mitra/webtheory/files/4623715/Img.upload.issue.zip)
