### ISSUE TITLE
Unable to save article, "Save" button is whitened out.

### ISSUE THREAD

**Issue by navkamplikar** [akash-mitra/webtheory#43]
![image](https://user-images.githubusercontent.com/57868502/76634924-97315280-6581-11ea-846f-d6b4d46e4a9d.png)

Error seen in the debug mode:
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
app.js:2 Uncaught (in promise) Error: Request failed with status code 500
    at t.exports (app.js:2)
    at t.exports (app.js:2)
    at XMLHttpRequest.d.onreadystatechange (app.js:2)

**Comment by akash-mitra** [comment]
This happened due to failure to embed videos. `EditorJSConverter` needs to change.
