### ISSUE TITLE
Template page gives `401 Unauthenticated` error

### ISSUE THREAD

**Issue by akash-mitra** [akash-mitra/webtheory#51]
In the blogabout.blog website, we get `401 Unauthenticated` error while trying to go to templates page.

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/3336242/77226846-5c00d600-6bb6-11ea-94e2-a823c07c661b.png">

This issue does not occur for other backend pages. This could be because certain routes are outside `'middleware' => ['auth:airlock']` auth group.

**Comment by sarubhai** [comment]
Cannot Reproduce. May be your backend code did php artisan cache and new airlock csrf is not available in frontend.

**Comment by akash-mitra** [comment]
This was because I was logged out. However, when I am logged out I can still access `/app/pages` - which should not have happened. As mentioned before, This could be because certain routes are outside `'middleware' => ['auth:airlock']` auth group. Please bring them in.
