### ISSUE TITLE
Login fails and takes to 419|page expired screen

### ISSUE THREAD

**Issue by navkamplikar** [akash-mitra/webtheory#57]
Login fails and takes to 419|page expired screen
[LoginIssue.zip](https://github.com/akash-mitra/webtheory/files/4507663/LoginIssue.zip)

**Comment by sarubhai** [comment]
Fixed in App\Exceptions\ExceptionHandler

if ($exception instanceof TokenMismatchException) {
    return back()->withInput()->with('csrf_error', "Please try again.");
}
