### ISSUE TITLE
Login model is not showing multiple service providers although they are enabled

### ISSUE THREAD

**Issue by navkamplikar** [akash-mitra/webtheory#59]
![image](https://user-images.githubusercontent.com/57868502/80824239-9c6d5e00-8c10-11ea-92e2-7842569b34e5.png)

screenshot from setting 
![image](https://user-images.githubusercontent.com/57868502/80824294-bc048680-8c10-11ea-8221-6392a9cc4ddc.png)

**Comment by akash-mitra** [comment]
we won't be giving LinkedIn at this moment
