### ISSUE TITLE
User with author role is able to see Add and Delete user options, but they do not function

### ISSUE THREAD

**Issue by navkamplikar** [akash-mitra/webtheory#62]
We either need to disable access to create and amend existing users by Author or Grant permissions to  perform the operation as of now I see errors doing the same.
Create new :
![image](https://user-images.githubusercontent.com/57868502/81468231-db06a800-9210-11ea-9668-aea72eaae9e2.png)

Delete user: 
I was asked for confirmation before getting into this error.
confirmation message pop-up 
![image](https://user-images.githubusercontent.com/57868502/81468279-186b3580-9211-11ea-9cc1-e604b5d078f4.png)

error msg:
![image](https://user-images.githubusercontent.com/57868502/81468258-fa9dd080-9210-11ea-9b67-fd738591de2e.png)

**Comment by sarubhai** [comment]
Hidden options create, trashed view & save button using v-if.

Profile update should happen for frontend for both registered user & author. 
Need to remove Profile api end-points modify to web endpoints

Backend provision to update users profile & role is only reserved to author
