### ISSUE TITLE
Table in editor is not having delete rows/ columns options. Am I missing anything while using it?

### ISSUE THREAD

**Issue by navkamplikar** [akash-mitra/webtheory#63]
Table in editor is not having delete rows/ columns options. Am I missing anything while using it?

[WebTheory - Admin - Google Chrome 2020-05-10 22-46-35.zip](https://github.com/akash-mitra/webtheory/files/4605824/WebTheory.-.Admin.-.Google.Chrome.2020-05-10.22-46-35.zip)

**Comment by akash-mitra** [comment]
#65, #66
