### ISSUE TITLE
Intro section missing the scroll bar

### ISSUE THREAD

**Issue by navkamplikar** [akash-mitra/webtheory#67]
In  one example, I have more than 2 rows in Intro section but I cant see a scroll bar to go down to next level. If not scrollbar but there may be some indication to show there are lines below.

![image](https://user-images.githubusercontent.com/57868502/81772085-7486d000-9517-11ea-942d-986cc3ab8928.png)

**Comment by akash-mitra** [comment]
On click the section will now expand and display the whole content
